Обратная сторона реальности
htmlacademy-react/1542653-what-to-watch-10 pull request #5
Opened 2022-07-24 15:02 UTC by YourfriendRND

- Добавил моки для фильмов;
- Передал моковые данные в необходимые компоненты через пропсы.
- Связал страницы приложения с помощью Link
- Вынес форму ревью фильма в отдельный компонент и реализовал сохранение введённых в форму данных в state компонента.

2022-07-26 06:09 UTC, yurylavrukhin requested changes
круто получилось, мне нравится 👍

2022-07-26 06:09 UTC, yurylavrukhin commented on project/src/pages/movie-screen/movie-screen.tsx
> +  const targetFilm = filmList.find((film) => film.id === Number(queryParam.id));
давай, если фильм не найден - редиректить на 404

сделай это, пожалуйста 🙏 

сейчас страница выглядит так и это плохое поведение потому что пользователь не поймёт что произошло
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/26966797/180934636-172c28d2-b251-4c2e-9aed-2a37ae23c117.png">

2022-07-26 06:09 UTC, yurylavrukhin commented on project/src/pages/movie-screen/movie-screen.tsx
> +      <section className="film-card film-card--full" style={{ background: targetFilm?.backgroundColor }}>
тогда в разметке не нужно будет использовать optional chaining `?.`

2022-07-26 06:09 UTC, yurylavrukhin commented on project/src/pages/movie-screen-review/movie-screen-review.tsx
> +  const targetFilm = filmList.find((film) => film.id === Number(queryParam.id));
давай, если фильм не найден - редиректить на 404

сделай это, пожалуйста 🙏

сейчас страница выглядит так и это плохое поведение потому что пользователь не поймёт что произошло
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/26966797/180934899-3378c932-e47a-4869-b5df-3d6382a1d389.png">

вот роут для тестирования
http://localhost:3000/films/99/review

2022-07-26 06:09 UTC, yurylavrukhin commented on project/src/pages/player-screen/player-screen.tsx
> +  const targetFilm = filmList.find((film) => film.id === Number(queryParam.id));
обработай случай если фильм не найден - редиректни на 404

2022-07-27 04:02 UTC, yurylavrukhin requested changes
очень хорошо, почти отлично 🙂

2022-07-27 04:02 UTC, yurylavrukhin commented on project/src/pages/movie-screen-review/movie-screen-review.tsx
> +            <img src={targetFilm.backgroundImage} alt={targetFilm?.name} />
излишний `?.`

2022-07-27 04:02 UTC, yurylavrukhin commented on project/src/pages/player-screen/player-screen.tsx
> +            <div className="player__name">{targetFilm?.name}</div>
излишний `?.`

2022-07-27 04:02 UTC, yurylavrukhin commented on project/src/pages/movie-screen-review/movie-screen-review.tsx
> +    : <UnexistScreen />;
здесь тоже сделай 2 return в теле компонента вместо тернарного оператора

2022-07-27 04:02 UTC, yurylavrukhin commented on project/src/pages/player-screen/player-screen.tsx
> +    : <UnexistScreen />;
ternary -> 2 return statements ☺️

2022-07-27 17:30 UTC, YourfriendRND commented
кнопка Play стала ссылкой после оборота ее в Link и соответственно взяла стили ссылки (с синим подчеркиванием) - убрал данные стили.

2022-07-29 05:48 UTC, yurylavrukhin approved these changes

2022-07-29 05:48 UTC, merged