Больше подробностей (часть 1)
htmlacademy-react/1542653-what-to-watch-10 pull request #6
Opened 2022-07-30 16:48 UTC by YourfriendRND

- Добавил компонент видеоплеер. 
- Добавил возможность воспроизводить превью фильма по наведению на карточку фильму на главном экране приложения.

2022-07-31 04:35 UTC, yurylavrukhin requested changes
обсудили в личке что поправить ☺️

2022-07-31 04:35 UTC, yurylavrukhin commented on project/src/components/film-card/film-card.tsx
> +  const [timer, setTimer] = useState<NodeJS.Timeout | null>(null);
тип `number | null`
<img width="289" alt="image" src="https://user-images.githubusercontent.com/26966797/182010274-e077f109-cac4-46c5-8f1d-14fe2cf156a5.png">

2022-07-31 04:35 UTC, yurylavrukhin commented on project/src/components/film-list/film-list.tsx
> +  };
эту логику переместить стоит в карточку фильма

2022-08-01 17:31 UTC, YourfriendRND commented
Внес исправления в соответствии с рекомендациями.

2022-08-02 03:39 UTC, yurylavrukhin approved these changes

2022-08-02 03:39 UTC, merged